/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package installer;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testApp() {
        App classUnderTest = new App();
        // TODO test urls used are valid
}
